//created on: 28/01/2021
package com.sample.rules

//list any import classes here.
import com.sample.droolscours.Account;
import com.sample.droolscours.CashFlow;
import com.sample.droolscours.AccountingPeriod;
import com.sample.utils.OutputDisplay;

//declare any global variables here
global OutputDisplay showResults;

rule "Credit rule"
	when
		$cash : CashFlow( $aDate : date, $no : accountNo, type == CashFlow.CREDIT )
		$acc : Account( accountNo == $no )
		$period : AccountingPeriod( startDate <= $aDate && endDate >= $aDate )
	then
		$acc.setBalance( $acc.getBalance() + $cash.getAmount() );
		showResults.showText("Account no "+ $acc.getAccountNo() + " has now a balance of " + $acc.getBalance());
end

rule "Debit rule"
	when
		$cash : CashFlow( $aDate : date, $no : accountNo, type == CashFlow.DEBIT )
		$acc : Account( accountNo == $no )
		$period : AccountingPeriod( startDate <= $aDate && endDate >= $aDate )
	then
		$acc.setBalance( $acc.getBalance() - $cash.getAmount() );
		showResults.showText("Account no "+ $acc.getAccountNo() + " has now a balance of "+ $acc.getBalance());
end



